import fs from 'node:fs';
import path from 'node:path';
import { stringify } from 'yaml';

const ROOT = process.cwd();
type Seed = readonly [string, string, string, string[], string, string];
type Group = { collection: string; taxonomy: Record<string, string[]>; tags: string[]; cases: Seed[] };
const groups: Group[] = [
  { collection: 'health', tags: ['医疗健康', '科普', '服务设计'], taxonomy: { deliverable: ['educational-visual', 'ui-interface'], medium: ['vector-graphic'], workflow: ['text-to-image'], capability: ['layout-hierarchy', 'data-visualization', 'instruction-following'], model: ['universal', 'gpt-image'] }, cases: [
    ['patient-care-dashboard', '患者照护看板', '帮助护理团队快速识别患者状态与待办事项。', ['clinic_name', 'care_unit'], 'Design a calm clinical care dashboard for {{clinic_name}} in {{care_unit}}. Show patient status cards, medication schedule, alerts, and a compact task timeline. Human-centered healthcare UI, accessible hierarchy, no real patient data, no logos, no watermark.', 'Modern healthcare dashboard with teal clinical interface cards, gentle white background, abstract patient metrics without readable text, polished UI case cover.'],
    ['medical-anatomy-poster', '人体结构科普海报', '用清晰的层级与图示解释人体结构。', ['body_system', 'audience_age'], 'Create an educational anatomy poster explaining {{body_system}} for {{audience_age}}. Use one central anatomical-style illustration, clear callout zones, sequential visual explanation, and friendly scientific accuracy. No readable text, no watermark.', 'Elegant medical anatomy educational poster, central illustrated human organ system with clean callout lines and blue-green scientific palette, no readable text.'],
    ['wellness-habit-tracker', '健康习惯追踪器', '以可执行小目标和趋势反馈支持日常健康习惯。', ['habit_focus', 'daily_target'], 'Design a friendly wellness habit tracker for {{habit_focus}} with {{daily_target}}. Include one motivating daily action, a weekly trend, a gentle progress visualization, and supportive micro-interactions. Warm mobile UI, no readable text, no watermark.', 'Warm wellness mobile app interface, circular habit tracker, soft peach and mint palette, modern health design, no readable text.'],
    ['pharmacy-packaging-guide', '药品包装识别指南', '帮助用户区分药品包装信息层级与安全提醒。', ['medicine_category', 'safety_message'], 'Create a packaging guidance board for {{medicine_category}} with an emphasis on {{safety_message}}. Show unbranded cartons, information hierarchy zones, dosage-form icons, and visible safety-color logic. Clear educational packaging design, no readable text, no watermark.', 'Professional pharmaceutical packaging guidance board with blank cartons, safety color blocks, clinical editorial design, no readable text.'],
    ['mental-health-resource-page', '心理健康资源页', '为寻求支持的用户提供安全温和的资源导航界面。', ['support_theme', 'primary_action'], 'Design a supportive mental health resource page about {{support_theme}}. Prioritize {{primary_action}}, calming visual rhythm, crisis-resource area, self-guided exercises, and privacy-forward language zones. Gentle inclusive UI, no readable text, no watermark.', 'Gentle mental health support webpage visual, soft lavender and warm cream cards, calm abstract shapes, no readable text.'],
  ] },
  { collection: 'education', tags: ['教育', '学习体验', '知识表达'], taxonomy: { deliverable: ['educational-visual', 'document-publishing'], medium: ['illustration', 'vector-graphic'], workflow: ['text-to-image'], capability: ['layout-hierarchy', 'instruction-following', 'text-rendering'], model: ['universal', 'gpt-image'] }, cases: [
    ['language-learning-cards', '语言学习卡片', '将词汇、语境和记忆提示组织为成组学习卡片。', ['language_pair', 'topic'], 'Create a set of language-learning flashcards for {{language_pair}} about {{topic}}. Balance illustration, word placeholder, example-sentence geometry, and recall cue. Friendly editorial learning design, no readable text, no watermark.', 'Colorful language learning flashcards with playful illustrations, blank text fields, tidy educational editorial design.'],
    ['museum-exhibit-panel', '博物馆展陈信息板', '用展品图像与时间线讲述一段历史主题。', ['exhibit_theme', 'historical_period'], 'Design a museum exhibit information panel about {{exhibit_theme}} in {{historical_period}}. Combine one artifact hero image, timeline, contextual map shape, and short explanatory zones. Sophisticated cultural publishing design, no readable text, no watermark.', 'Museum exhibition panel design, artifact silhouette, timeline motifs and warm archival paper texture, no readable text.'],
    ['math-concept-explainer', '数学概念图解', '将抽象数学关系转换为直观的视觉步骤。', ['math_topic', 'real_world_example'], 'Create an approachable math explainer for {{math_topic}} using {{real_world_example}}. Build a step-by-step visual model, one clear formula placeholder, and a final practical takeaway. Crisp modern education graphic, no readable text, no watermark.', 'Modern mathematical concept infographic, geometric diagrams and bright primary accents on white, no readable text.'],
    ['student-portfolio-cover', '学生作品集封面', '为创意专业学生建立克制有辨识度的作品集封面。', ['discipline', 'student_name'], 'Design a portfolio cover for a {{discipline}} student named {{student_name}}. Use an original abstract visual language, elegant title zone, material detail, and a memorable restrained composition. Contemporary editorial cover, no readable text, no watermark.', 'Creative student portfolio cover, bold abstract geometric composition, premium paper texture, no readable text.'],
    ['interactive-workshop-board', '工作坊协作白板', '用于团队共创、观点收集与行动排序的协作板。', ['workshop_topic', 'team_size'], 'Create an interactive workshop board for {{workshop_topic}} with {{team_size}} participants. Organize warm-up, idea clusters, voting dots, decision matrix, and next actions through a clear visual flow. Collaborative visual facilitation, no readable text, no watermark.', 'Colorful collaborative workshop whiteboard, sticky note clusters, flow arrows and voting dots, no readable text.'],
  ] },
  { collection: 'game', tags: ['游戏设计', '虚拟世界', '概念艺术'], taxonomy: { deliverable: ['scene-storytelling', 'portrait-character'], medium: ['illustration', '3d-render'], workflow: ['text-to-image', 'series-consistency'], capability: ['spatial-reasoning', 'subject-consistency', 'material-lighting'], model: ['universal', 'midjourney', 'stable-diffusion'] }, cases: [
    ['game-key-art', '游戏主视觉概念', '用单一强叙事画面传达游戏世界与核心冲突。', ['game_genre', 'central_conflict'], 'Create original game key art for a {{game_genre}} game centered on {{central_conflict}}. Use a dramatic hero silhouette, layered world scale, cinematic lighting, and one clear focal direction. No text, no existing IP, no watermark.', 'Epic original game key art, lone hero silhouette against a vast fantasy city, cinematic light, no text.'],
    ['isometric-game-environment', '等距游戏场景', '展示可探索区域、地标与互动节奏的等距场景。', ['biome', 'landmark'], 'Create an original isometric game environment in {{biome}} featuring {{landmark}}. Include readable pathing, layered exploration points, tiny environmental storytelling, and coherent asset language. Stylized game art, no text, no watermark.', 'Detailed isometric fantasy game environment with winding paths, landmark tower and rich miniature assets, no text.'],
    ['racing-game-garage', '赛车游戏车库', '呈现车辆定制、性能信息和沉浸氛围的游戏车库。', ['car_style', 'garage_mood'], 'Create a racing-game garage scene for a {{car_style}} vehicle with a {{garage_mood}} atmosphere. Show a hero vehicle, tools, tuning parts, colored ambient lighting, and a clear upgrade-display area. Original game environment, no logos, no watermark.', 'Neon racing game garage, unbranded custom sports car, glowing tools and atmospheric purple light, no text.'],
    ['cozy-game-cabin', '治愈游戏小屋', '强调日常细节与舒适节奏的治愈系游戏场景。', ['season', 'cabin_activity'], 'Create a cozy original game scene of a cabin during {{season}}, focused on {{cabin_activity}}. Layer tactile props, warm interior light, nature outside, and charming interactive details. Gentle stylized illustration, no text, no watermark.', 'Cozy game cabin interior in rainy autumn, glowing fireplace and tiny craft details, stylized illustration, no text.'],
    ['card-game-deck-concept', '卡牌游戏卡组概念', '为原创卡牌游戏建立统一的稀有度与视觉系统。', ['game_theme', 'rarity_palette'], 'Design an original card-game deck concept for {{game_theme}} using {{rarity_palette}}. Show a hero card, three supporting cards, card-back pattern, and a coherent frame system. Premium fantasy graphic design, no readable text, no watermark.', 'Original collectible card game deck, ornate frames and glowing rarity colors, no readable text, no franchise.'],
  ] },
  { collection: 'fashion', tags: ['时尚', '造型', '零售视觉'], taxonomy: { deliverable: ['poster-editorial', 'product-commerce'], medium: ['photography', 'mixed-media'], workflow: ['text-to-image'], capability: ['material-lighting', 'layout-hierarchy', 'instruction-following'], model: ['universal', 'gpt-image', 'midjourney'] }, cases: [
    ['fashion-lookbook-cover', '时尚型录封面', '以强造型和排版留白呈现季节性时尚主题。', ['season_theme', 'styling_direction'], 'Create a fashion lookbook cover for {{season_theme}} with {{styling_direction}}. Use one editorial figure, bold composition, tactile fabric detail, and generous title-safe space. Fashion magazine photography, no readable text, no logo, no watermark.', 'High-fashion lookbook cover, editorial figure in sculptural clothing, bold shadow and title-safe space, no readable text.'],
    ['watch-campaign-image', '腕表广告主视觉', '通过微距材质和时间感营造高端腕表广告。', ['watch_style', 'setting'], 'Create a luxury campaign image for a {{watch_style}} watch in {{setting}}. Focus on precision metal details, elegant reflections, believable scale, and an art-directed still-life composition. No branding, no readable text, no watermark.', 'Luxury wristwatch campaign, macro metal reflections on dark stone, elegant amber light, no branding.'],
    ['fashion-editorial-collage', '时尚编辑拼贴', '将人物、材质与图形元素组合为潮流编辑拼贴。', ['style_era', 'color_story'], 'Create a fashion editorial collage inspired by {{style_era}} with {{color_story}}. Combine original model photography, fabric scans, hand-drawn marks, and controlled typography placeholders. Premium mixed-media design, no readable text, no watermark.', 'Fashion editorial collage with layered fabric textures, model cutouts and graphic marks, no readable text.'],
    ['boutique-window-display', '精品店橱窗陈列', '以戏剧化光线和层叠商品打造高识别度橱窗。', ['product_category', 'display_mood'], 'Design a boutique window display for {{product_category}} with a {{display_mood}} mood. Use sculptural props, layered elevation, focused lighting, and blank product forms. Luxury retail visual merchandising, no logos, no watermark.', 'Luxury boutique window display, sculptural plinths and glowing product forms, deep burgundy mood, no logos.'],
    ['streetwear-drop-poster', '街头服饰发售海报', '用强节奏的视觉语言表现街头服饰新品发售。', ['drop_theme', 'accent_color'], 'Create an original streetwear drop poster for {{drop_theme}} with {{accent_color}}. Use a strong garment silhouette, gritty print texture, kinetic type placeholder blocks, and a bold vertical composition. No readable text, no brand logos, no watermark.', 'Streetwear launch poster, oversized jacket silhouette, gritty screenprint texture and acid green accents, no readable text.'],
  ] },
  { collection: 'food', tags: ['餐饮', '食物摄影', '品牌内容'], taxonomy: { deliverable: ['product-commerce', 'poster-editorial'], medium: ['photography'], workflow: ['text-to-image'], capability: ['material-lighting', 'layout-hierarchy', 'product-fidelity'], model: ['universal', 'gpt-image', 'nano-banana'] }, cases: [
    ['restaurant-menu-cover', '餐厅菜单封面', '用材质、色彩与留白建立餐厅菜单第一印象。', ['cuisine_style', 'restaurant_mood'], 'Design a menu cover for a {{cuisine_style}} restaurant with a {{restaurant_mood}} mood. Use one refined food-or-material still life, elegant title space, and tactile print detail. Editorial hospitality design, no readable text, no watermark.', 'Elegant restaurant menu cover with moody food still life and tactile paper texture, no readable text.'],
    ['cocktail-campaign-shot', '鸡尾酒广告摄影', '以玻璃、高光与果香元素塑造精致鸡尾酒主视觉。', ['cocktail_style', 'hero_color'], 'Create a premium cocktail campaign image for a {{cocktail_style}} drink using {{hero_color}}. Show one crafted glass, expressive garnish, liquid refraction, and cinematic bar light. High-end beverage photography, no text, no watermark.', 'Premium cocktail advertising image, jewel-toned drink in sculptural glass, dramatic bar light, no text.'],
    ['bakery-social-series', '烘焙社媒系列', '为烘焙新品打造统一色调的社媒内容系列。', ['pastry_type', 'color_palette'], 'Create a square social-media visual series for {{pastry_type}} using {{color_palette}}. Feature one hero pastry, playful supporting crumbs or ingredients, and clear copy-safe composition. Bright bakery photography, no readable text, no watermark.', 'Playful bakery social campaign, glossy pastry on pastel set with crumbs and fruit, no readable text.'],
    ['farm-to-table-story', '农场到餐桌叙事图', '通过食材、人物与产地串起从农场到餐桌的故事。', ['ingredient', 'farm_setting'], 'Create a farm-to-table editorial story image featuring {{ingredient}} from {{farm_setting}}. Combine harvest texture, hands at work, and a beautiful finished dish through one natural narrative composition. Authentic food photography, no watermark.', 'Farm-to-table editorial scene, hands harvesting herbs beside a rustic prepared dish, warm natural light, no text.'],
    ['tea-ceremony-editorial', '茶席编辑摄影', '以器物、蒸汽和自然材料建立克制的东方茶席画面。', ['tea_type', 'surface_material'], 'Create a quiet tea ceremony editorial image featuring {{tea_type}} on {{surface_material}}. Show handmade vessels, rising steam, subtle natural shadows, and calm negative space. Refined still-life photography, no text, no watermark.', 'Quiet tea ceremony still life, handmade ceramics and steam on a dark wood surface, refined editorial photography.'],
  ] },
  { collection: 'social', tags: ['社交媒体', '营销内容', '品牌传播'], taxonomy: { deliverable: ['poster-editorial', 'brand-identity'], medium: ['vector-graphic', 'mixed-media'], workflow: ['text-to-image'], capability: ['layout-hierarchy', 'text-rendering', 'instruction-following'], model: ['universal', 'gpt-image'] }, cases: [
    ['podcast-cover-art', '播客封面视觉', '通过强识别图形与氛围建立播客节目的封面。', ['podcast_topic', 'mood'], 'Create square podcast cover art for {{podcast_topic}} with a {{mood}} mood. Use one memorable original symbol, high-contrast composition, and title-safe area. Contemporary audio-brand design, no readable text, no logo, no watermark.', 'Bold square podcast cover, abstract soundwave sculpture in rich gradient color, no readable text.'],
    ['creator-media-kit', '创作者媒体包', '展示创作者数据、合作内容和视觉调性的媒体包。', ['creator_niche', 'audience_focus'], 'Design a media-kit one-pager for a {{creator_niche}} creator focused on {{audience_focus}}. Include hero portrait placeholder, audience metrics, collaboration tiles, and content samples. Stylish editorial layout, no readable text, no watermark.', 'Creator media kit design, editorial portrait placeholder and elegant metric cards, no readable text.'],
    ['live-stream-overlay', '直播互动叠层', '为直播画面提供弹幕、互动和嘉宾信息的叠层设计。', ['stream_topic', 'visual_mood'], 'Design a live-stream overlay for {{stream_topic}} with a {{visual_mood}} direction. Include host frame, chat zone, lower third, audience reaction strip, and event cue shapes. Modern broadcast graphics, no readable text, no real platform logos, no watermark.', 'Modern livestream overlay design, neon broadcast frames and chat panels, no readable text or logos.'],
    ['newsletter-hero-banner', '邮件通讯头图', '以简洁主题视觉增强邮件通讯的打开率与识别度。', ['newsletter_theme', 'visual_metaphor'], 'Create a wide newsletter hero banner for {{newsletter_theme}} using {{visual_metaphor}}. Make a singular clean editorial image with generous copy-safe space and refined palette. No readable text, no logo, no watermark.', 'Wide editorial newsletter banner, abstract visual metaphor with soft gradient and clean copy-safe area, no text.'],
    ['community-event-card', '社群活动宣传卡', '用友好且高辨识度的构图传播社群线下活动。', ['event_type', 'community_vibe'], 'Create a square community event card for {{event_type}} with a {{community_vibe}} vibe. Use welcoming people shapes, clear information hierarchy zones, and memorable color blocking. Friendly event graphic design, no readable text, no watermark.', 'Welcoming community event card, colorful abstract people and playful geometric shapes, no readable text.'],
  ] },
  { collection: 'business', tags: ['企业', '商业沟通', '运营管理'], taxonomy: { deliverable: ['document-publishing', 'ui-interface'], medium: ['vector-graphic'], workflow: ['text-to-image'], capability: ['data-visualization', 'layout-hierarchy', 'instruction-following'], model: ['universal', 'gpt-image'] }, cases: [
    ['sales-pipeline-dashboard', '销售漏斗看板', '帮助销售团队跟进阶段、预测收入与重点客户。', ['sales_team', 'revenue_goal'], 'Design a sales pipeline dashboard for {{sales_team}} pursuing {{revenue_goal}}. Show funnel stages, forecast chart, deal table, activity feed, and priority alerts. Credible business UI, no readable text, no real customer data, no watermark.', 'Polished sales pipeline dashboard, funnel chart and deal cards in navy and aqua, no readable text.'],
    ['investor-pitch-deck-cover', '融资路演封面', '用强概念视觉与克制排版建立融资路演的第一印象。', ['company_theme', 'investment_stage'], 'Create an investor pitch deck cover for {{company_theme}} at {{investment_stage}}. Use a confident abstract growth metaphor, elegant title-safe composition, and credible business polish. No readable text, no real logo, no watermark.', 'Premium startup investor deck cover, abstract rising forms and midnight blue gradient, no readable text.'],
    ['team-offsite-agenda', '团队团建议程', '将目标、活动与休息节奏组织为一目了然的团队议程。', ['offsite_theme', 'duration'], 'Design a team offsite agenda for {{offsite_theme}} lasting {{duration}}. Organize welcome, workshops, meals, breaks, and reflection moments through a clear visual timeline. Friendly professional planning design, no readable text, no watermark.', 'Friendly team offsite agenda graphic, timeline cards and warm abstract landscape, no readable text.'],
    ['sustainability-report-spread', '可持续报告跨页', '以数据、图示与留白呈现企业可持续成果。', ['impact_area', 'reporting_year'], 'Create a sustainability report double-page spread about {{impact_area}} in {{reporting_year}}. Balance one impact visual, abstract charts, key metric zones, and calm natural color. Premium corporate editorial design, no readable text, no watermark.', 'Sustainability report spread, green data visualization and aerial nature texture, no readable text.'],
    ['recruitment-campaign-page', '招聘宣传页面', '以岗位价值、团队文化和真实氛围吸引候选人的招聘页。', ['company_type', 'talent_theme'], 'Design a recruitment campaign page for a {{company_type}} seeking {{talent_theme}}. Include culture imagery, role cards, growth narrative, and a clear application action. Modern human-centered career site UI, no readable text, no watermark.', 'Modern recruitment landing page, diverse team photography and clean job cards, no readable text.'],
  ] },
  { collection: 'visuals', tags: ['视觉图解', '地图', '流程设计'], taxonomy: { deliverable: ['infographic', 'educational-visual'], medium: ['vector-graphic'], workflow: ['text-to-image'], capability: ['data-visualization', 'spatial-reasoning', 'layout-hierarchy'], model: ['universal', 'gpt-image'] }, cases: [
    ['city-guide-map', '城市旅行导览图', '将路线、地标和推荐地点组织为可读城市导览。', ['city_theme', 'travel_interest'], 'Create an illustrated city guide map for {{city_theme}} focused on {{travel_interest}}. Show key landmarks, a walking route, neighborhood color zones, and small discovery icons. Charming editorial cartography, no readable text, no watermark.', 'Charming illustrated city guide map with landmark icons and winding route, no readable text.'],
    ['customer-journey-map', '用户旅程地图', '通过触点、情绪和机会点描绘完整用户体验路径。', ['service_type', 'user_goal'], 'Design a customer journey map for {{service_type}} helping users achieve {{user_goal}}. Visualize stages, touchpoints, emotion curve, pain points, and opportunity zones. Clear service-design diagram, no readable text, no watermark.', 'Professional customer journey map with colored stages and emotion curve, no readable text.'],
    ['decision-tree-diagram', '决策树图解', '将复杂选择拆解成清晰可执行的判断路径。', ['decision_topic', 'key_criteria'], 'Create a decision-tree diagram for {{decision_topic}} based on {{key_criteria}}. Use a clear branching structure, visual yes-no nodes, outcome groups, and calm color coding. Accessible editorial diagram, no readable text, no watermark.', 'Clear decision tree infographic with branching colored nodes on warm white, no readable text.'],
    ['supply-chain-map', '供应链流程图', '展示从原料到交付的多环节供应链关系。', ['industry', 'delivery_goal'], 'Create a supply-chain process map for {{industry}} focused on {{delivery_goal}}. Show source, production, logistics, fulfillment, and feedback loops with connected icons and a readable flow. Modern industrial infographic, no readable text, no watermark.', 'Modern supply chain infographic, connected factory warehouse transport icons, no readable text.'],
    ['travel-itinerary-board', '旅行行程规划板', '将每日路线、活动和住宿节奏整理为旅行行程板。', ['destination_style', 'trip_length'], 'Design a travel itinerary board for a {{destination_style}} trip lasting {{trip_length}}. Show daily route cards, time blocks, stay markers, packing cues, and a clear map-inspired rhythm. Stylish travel planning graphic, no readable text, no watermark.', 'Stylish travel itinerary board with day cards, map motifs and sunny color palette, no readable text.'],
  ] },
  { collection: 'creative', tags: ['创意实验', '材质', '抽象视觉'], taxonomy: { deliverable: ['illustration-art', 'poster-editorial'], medium: ['mixed-media', '3d-render'], workflow: ['text-to-image'], capability: ['material-lighting', 'instruction-following', 'spatial-reasoning'], model: ['universal', 'midjourney', 'stable-diffusion'] }, cases: [
    ['abstract-material-study', '抽象材质研究', '探索玻璃、金属、液体等材质关系的抽象视觉研究。', ['material_pair', 'color_mood'], 'Create an abstract material study combining {{material_pair}} with a {{color_mood}} color mood. Emphasize tactile surface interaction, controlled light, and a refined gallery composition. No text, no watermark.', 'Abstract material study, molten chrome meeting translucent glass, rich violet and cyan light, gallery-quality render.'],
    ['surreal-fashion-scene', '超现实时尚场景', '将时尚人物置入不合常理却统一的超现实空间。', ['fashion_element', 'surreal_setting'], 'Create a surreal fashion editorial scene with {{fashion_element}} in {{surreal_setting}}. Use one elegant figure, impossible but coherent spatial logic, and polished art direction. No text, no logos, no watermark.', 'Surreal fashion scene, elegant figure on floating stairs in a soft pink sky, high-end editorial photography.'],
    ['kinetic-typography-poster', '动态文字海报概念', '以文字节奏和抽象运动形态表达活动能量。', ['event_energy', 'color_contrast'], 'Create a kinetic typography poster concept expressing {{event_energy}} through {{color_contrast}}. Use dynamic letter-like shapes and energetic graphic motion while leaving actual words unreadable. Experimental print design, no watermark.', 'Experimental kinetic typography poster, abstract letter-like ribbons in vivid color contrast, no readable text.'],
    ['nature-macro-abstraction', '自然微观抽象', '从自然微观结构中提取具有艺术感的抽象视觉。', ['natural_subject', 'light_condition'], 'Create a macro abstract image inspired by {{natural_subject}} under {{light_condition}}. Reveal organic pattern, rich texture, and unexpected scale through museum-quality composition. No text, no watermark.', 'Macro abstract nature image, iridescent leaf cells and dew under soft side light, gallery photography.'],
    ['ceramic-sculpture-study', '陶瓷雕塑研究', '用形体、釉色和光线呈现原创陶瓷雕塑系列。', ['sculpture_language', 'glaze_palette'], 'Create a studio study of original ceramic sculptures using {{sculpture_language}} and {{glaze_palette}}. Arrange several forms with nuanced shadow, pedestal scale, and gallery lighting. No text, no watermark.', 'Gallery ceramic sculpture study, sculptural organic forms with glossy cobalt glaze on plinths, no text.'],
  ] },
  { collection: 'finance', tags: ['金融', '地产', '数据展示'], taxonomy: { deliverable: ['ui-interface', 'infographic'], medium: ['vector-graphic', 'photography'], workflow: ['text-to-image'], capability: ['data-visualization', 'layout-hierarchy', 'instruction-following'], model: ['universal', 'gpt-image'] }, cases: [
    ['personal-finance-overview', '个人财务总览', '将收入、支出和储蓄目标整合为清晰个人财务界面。', ['financial_goal', 'time_horizon'], 'Design a personal finance overview for {{financial_goal}} over {{time_horizon}}. Show cash flow, budget categories, savings progress, and one actionable insight. Calm premium finance UI, no readable text, no real account data, no watermark.', 'Premium personal finance app dashboard, elegant charts and savings rings in emerald and navy, no readable text.'],
    ['real-estate-listing-hero', '房产展示主视觉', '用空间、光线和居住想象呈现高端房产展示。', ['property_type', 'location_mood'], 'Create a premium real-estate listing hero for a {{property_type}} with a {{location_mood}} atmosphere. Show architectural character, indoor-outdoor connection, soft sunset light, and clear copy-safe space. Editorial property photography, no text, no watermark.', 'Premium real estate listing hero, contemporary home opening to a tranquil garden at golden hour, no text.'],
    ['market-trend-report', '市场趋势报告', '以图表、指标与封面视觉呈现市场趋势洞察。', ['market_sector', 'trend_theme'], 'Create a market trend report cover and data visual system for {{market_sector}} about {{trend_theme}}. Use a sophisticated abstract chart motif, key metric zones, and a precise editorial grid. No readable text, no logo, no watermark.', 'Sophisticated market trend report cover, abstract ascending data lines in cyan and violet, no readable text.'],
    ['mortgage-comparison-tool', '贷款方案对比工具', '帮助用户在不同房贷方案之间进行清晰比较。', ['loan_type', 'decision_focus'], 'Design a mortgage comparison tool for {{loan_type}} focused on {{decision_focus}}. Show side-by-side plan cards, payment timeline, rate sensitivity chart, and clear recommendation state. Trustworthy financial UI, no readable text, no watermark.', 'Mortgage comparison interface, elegant side-by-side finance cards and payment chart, no readable text.'],
    ['investment-portfolio-story', '投资组合叙事图', '通过资产分布与长期目标表达投资组合策略。', ['portfolio_style', 'investment_goal'], 'Create an investment portfolio story visual for {{portfolio_style}} pursuing {{investment_goal}}. Combine allocation rings, long-term horizon landscape, and a simple risk-return relationship. Premium editorial finance infographic, no readable text, no watermark.', 'Premium investment portfolio infographic, elegant allocation rings floating over a calm horizon landscape, no readable text.'],
  ] },
];

const manifest: Array<{ id: string; cover: string }> = [];
let created = 0;
for (const group of groups) for (const [id, title, summary, variables, prompt, cover] of group.cases) {
  const directory = path.join(ROOT, 'library', 'cases', group.collection, id);
  manifest.push({ id, cover });
  if (fs.existsSync(path.join(directory, 'case.yaml'))) continue;
  fs.mkdirSync(directory, { recursive: true });
  fs.writeFileSync(path.join(directory, 'case.yaml'), stringify({ id, title, summary, taxonomy: group.taxonomy, tags: [...group.tags, title], license: { prompt: 'CC0-1.0', reference: 'none' }, source: { kind: 'original', url: null, rights_note: 'Original repository content.' }, prompt: { language: 'en', variables }, evaluation: { status: 'draft', tested_models: [], last_verified: null, limitations: ['Use the prompt as a starting point and review model output before production use.'] } }));
  fs.writeFileSync(path.join(directory, 'prompt.md'), `# ${title}\n\n## Prompt\n\n${prompt}\n\n## 使用说明\n\n${summary}\n`);
  created += 1;
}
fs.writeFileSync(path.join(ROOT, 'tmp-second-cover-manifest.json'), JSON.stringify(manifest));
console.log(`Created ${created} second-wave cases.`);
